### ISSUE TITLE
Exact matching syntax

### ISSUE THREAD

**Issue by ryardley** [ryardley/pdsl#40]
## Exact Matching for Objects

I think using flow's exact matching syntax would be useful for specifying when an object cannot have any other properties except for those provided.

I propose the following for consideration:

```js
p`{name, age}`({name: 'Michael', age: 27, pet: 'Cat'});// true
p`{|name, age|}`({name: 'Michael', age: 27, pet: 'Cat'});// false
```

## Exact Matching for Arrays

Currently the Array matching syntax `[a,b,c]` will return true when the array contains one or more of the values provided. 

I propose the following for consideration:

```js
// exact match unordered
p`[|6, 'foo'|]`([6, 'foo']); // true
p`[|6, 'foo'|]`(['foo', 6]); // true
p`[|6, 'foo'|]`([6, 7, 'foo']); // false 

// ordered 
p`[||6, 'foo'||]`(['foo', 6]); // false
```

This is reminiscent of the exact Object syntax in flow which is why I like it.

**Comment by ZabutonNage** [comment]
While it's probably way too late for fundamental changes, I would still like to share my thoughts on this if you don't mind.

Being someone who prefers being explicit about assertions, I would actually favour the _exact matching_ to be the default behaviour. If I define a predicate (or pattern or whatever) that goes like
`{name, age}`,
then `{name: 'Michael', age: 27, pet: 'Cat'}` does not match.
I didn't ask for `pet`.

As an alternative to duck typing, wildcards could be utilised. They allow even more detailed control over your pattern and are very expressive. There could be a _match exactly one item_ wildcard, say `_`. And a _match any amount of items (including zero)_, say `__` (double underscore).
```js
p`{name, age}`({name: 'Michael', age: 27, pet: 'Cat'}); // false, too many properties
p`{name, age, _}`({name: 'Michael', age: 27, pet: 'Cat'}); // true
p`{name, _, _}`({name: 'Michael', age: 27, pet: 'Cat'}); // true
p`{name, age, _, _}`({name: 'Michael', age: 27, pet: 'Cat'}); // false, expects 4 properties
p`{name, age, _, __}`({name: 'Michael', age: 27, pet: 'Cat'}); // true, '__' matches 0 or more
p`{_, __}`({name: 'Michael', age: 27, pet: 'Cat'}); // true, matches any object with at least one property
```

The same would apply to arrays, while the _ordered_ exact matching would be default here.

With this approach I find it more obvious what results to expect. If you have never seen this kind of syntax before, with the wildcard syntax you would (arguably) have a better chance to make a correct guess.

What are your thoughts on this?

**Comment by ryardley** [comment]
Hey thanks @ZabutonNage  I really appreciate your input! 

Exact matching is important functionality and needs to be implemented and I understand why you would like exact matching to be the default. However I have a couple of counter points here. 

1. Exact matching is less versatile than loose matching which is why I implemented loose matching first and have it as default. 

2. Exact matching by default adds a minor amount of computational overhead by default as we need to check the number of properties for every nested object.

3. The underscore syntax is not as familiar to JavaScript developers as the Flow bar syntax. The above proposal requires no extra cognitive leap from Flow's syntax.

```ts
// @flow
type Loose = {foo:string, bar:number};
type Exact = {|foo:string, bar:number|};

const loose = p`{foo:string, bar:number}`;
const exact = p`{|foo:string, bar:number|}`;
```

Underscores are by convention usually used as missing function input props which might be considered another divergence.

Having said all that I guess we could say the `__` suggestion is equivalent to `[k:string]:any` in TypeScript. 

```ts
// typescript
type Loose = {foo:string, bar:number, [k:string]:any};
type Exact = {foo:string, bar:number};

const loose = p`{foo:string, bar:number, __}`;
const exact = p`{foo:string, bar:number}`;
```

Lastly as you can't really easily check the number of rest properties in an object in Flow or TypeScript I am wondering as to whether or not the single `_`  would actually be useful?

**Comment by ryardley** [comment]
Having said all of that I am not totally closed off to the idea.

What about a rest parameter?

```ts
p`{ foo:string, bar:number, ... }`;
```

**Comment by ZabutonNage** [comment]
Hi @ryardley! Sorry for the late response.

Thank you for your consideration.

Oddly, I have always considered loose matching to be less versatile because you can't exclude values. To clarify, when I talk about _exact by default_, it always includes some form of wildcards. At least the "rest" one. Otherwise it would indeed be extremely daunting to match larger objects.
To be fair the proper equivalent to _exact + wildcards_ would then probably be _loose + exact notation_.
```js
{ looseByDef } == { exactByDef, __ }
{| looseByDef |} == { exactByDef }
```
Which produces the same behaviour. Although after writing it out, I found the wildcard syntax more pleasant to type. Might be due to my keyboard layout.

Regarding the concerns about computational overhead, even though I didn't do any measurements, this might be not so much of an issue. Whether the syntax becomes `{| foo |}` or `{ foo, ... }`, every level of nesting will always have to detect looseness/strictness. Once looseness is detected, it should be possible to short-circuit further computations, so I think there is a chance that it wouldn't make a difference.

The underscore syntax was not meant to be mandatory. I regularly pick it because it is very familiar to people with knowledge in Haskell/PureScript (like myself). I, for example, am not familiar with Flow syntax at all. I have also seen question marks as wildcards in some proposals but I would really like to avoid them. With the newly introduced optional chaining `?.` and nullish-coalescing `??` I'm expecting a LOT of question marks to appear in code from now. We don't need more.
`_` is easy to type (on my keyboard) and not as "noisy" as full-height characters.

I like the idea to use `{ foo: string, ... }` as the rest wildcard. This will be familiar to all JS devs. :+1: 

I'm not quite sure I understand your concerns in your fourth point. Is it about type annotations that have to reflect a matched object?
Haven't used TypeScript in a while but it still does duck-typing, doesn't it?
Wouldn't this be covered?
```ts
const single = p`{ foo:string, bar:number, _ }`;
type Loose = { foo:string, bar:number, [k:string]:any };
```

Even if it turns out the single wildcard is not that useful on objects or simply too difficult to integrate, it would certainly shine in arrays. Consider this
```js
const isSingletonArray = p`Array & { length: 1 }`;
// becomes
const isSingletonArray = p`[_]`;
```
Even at four items length it still reads nicely.
```js
const is4ItemArray = p`Array & { length: 4 }`;
// becomes
const is4ItemArray = p`[_, _, _, _]`;
```
Of course this doesn't scale indefinitely, but the current syntax would remain available for larger arrays.

Is something like this currently possible?
```js
p`["foo", _, "baz"]`(["foo", 123, "baz"]);  // true
```

**Comment by ryardley** [comment]
@ZabutonNage I am starting to agree with you it might make more sense to be exact by default. 

Agree that single wildcard makes array length checking shorter - I find this very appealing. My last point was that both flow and typescript don't actually allow you to do single wildcard matching within objects. TypeScript allows this within arrays which is very useful. eg 

```ts
const foo:[number, number, string] = [1,2,'3'];
```

I would suggest we follow this lead with PDSL: 

```js
p`[number,number,string]`([1,2,'3']);// true
```

```js
p`[number,number,string]`([1,2,3,'4']);// false
```
```

Honestly I don't particularly like the flow syntax because it requires multiple symbols to show that we are dealing with an exact match. I just thought it made sense for familiarity's sake as Flow is loose matching first but if we go with exact matching by default we can drop it.

I am still not 100% sold on the single underscore as the token for a single exact match because it is often used as to denote an exception to provide an unused input argument in javascript linters when you have multiple args but only need the last one in a function definition. 

How do you feel about a `*` as the single arg wildcard? - reason being that it is reminiscent of glob syntax for a single filename component which everyone knows and if you squint it is sort of similar.

1. Stay loose by default - use the flow syntax for exact matching
1. Change to exact by default - use `...` and `*`
1. Use some kind of helper function to denote exact or loose matching and avoid incorporating it into the syntax. eg. 

Lastly no currently this would not work:

```js
p`["foo", _, "baz"]`(["foo", 123, "baz"]);  // true
```

However your proposal allows for it.

**Comment by ryardley** [comment]
Made this priority as it will be easier to make a breaking change now rather than later

**Comment by ZabutonNage** [comment]
I favour your first option, too.
While the `p.exact` syntax might have some potential as well, I'm not so sure how this could work with nested objects.

Using `*` as the single wildcard might be okay. I'm just not quite sure about its potential to cause confusion, though. I like the inspiration from glob syntax because it's a well-known pattern, but on the other hand it would be an additional source of influence. I don't think there is anything glob-like in JS so far, is there? Plus, `*` already exists in regex syntax which is built into JS. Another pattern-match kind of thing. But here it corresponds to `...`. I'm somewhat worried that those concepts might clash in people's minds.
When writing the examples below, I briefly switched into regex mode every time I saw `*`.

Going back to `_` once more, aren't we having this "don't care" situation in ``p`[1, _, 3]` ``? While we do care that something is there, we don't care what it is. The second element will not be relevant for this predicate.
In a function declaration like `.map(function(_, i) { /* ... */ })` you could think of the parameters as an array of values (actually they are in `arguments`). Here we also expect something to take up this space in order to get the parameters' positions right.
To me this feels close enough to be considered the same concept.

Before I go on, some examples of how I currently understand this feature. Using both `_` and `*` for demonstration. Let me know if you have this regex experience described above, too.
```js
p`[]`([1, 2])     // false
p`[*]`([1, 2])    // false
p`[*, *]`([1, 2]) // true
p`[number, number]`([1, 2, 3])         // false
p`[number, number, ...]`([1, 2, 3])    // true
p`[number, *, 3]`([1, NaN, 3])         // true
p`[_, number, _]`([NaN, 2])            // false
p`[*, number, *]`([NaN, 2, undefined]) // true

p`{}`({})        // true
p`{}`({ foo: 1}) // false
p`{...}`({})         // true
p`{...}`({ foo: 1 }) // true
p`{ * }`({ foo: 1, bar: 2 }) // not going to be implemented now
p`{ foo }`({ foo: 1 })     // true
p`{ foo }`({ foo: "bar" }) // true
p`{ foo: string }`({ foo: 1 })     // false
p`{ foo: string }`({ foo: "bar" }) // true
p`{ foo: { bar, ... } }`({ foo: { bar: 2 } }) // true
p`{ foo: { bar, ... } }`({ foo: { bar: 2, baz: 3 } }) // true
p`{ foo: { bar, ... } }`({ foo: { bar: 2, baz: 3 }, qux: 4 }) // false
```

Are you planning to introduce the following? I'm not sure whether this was for demonstration or an actual proposal.
```js
p`{ name: * }`;
```
I use this style in my JS pattern-matching implementation. But there I'm using actual objects instead of strings to form the pattern. Here I would be fine without. ``p`{ name }`;`` is nicely short and like native ES6 syntax. Wouldn't mind it being introduced either, but I think I wouldn't use it.

**Some experimenting with wildcard tokens**
Perhaps there are even better symbols for the wildcards we haven't thought about yet.
```js
p`[ ? ]`([ 1, 2 ])         // regex (-> false)
p`[ a, ? ]`([ 1, 2 ])      // regex
p`[ ?, b, ... ]`([ 1, 2 ]) // regex hybrid
p`[ ?, b, * ]`([ 1, 2 ])   // full regex

p`[ * ]`([ 1, 2 ])         // glob (-> false)
p`[ a, * ]`([ 1, 2 ])      // glob
p`[ *, b, ... ]`([ 1, 2 ]) // glob hybrid
p`[ *, b, ** ]`([ 1, 2 ])  // full glob

p`[ _ ]`([ 1, 2 ])         // haskell (-> false)
p`[ a, _ ]`([ 1, 2 ])      // haskell
p`[ _, b, ... ]`([ 1, 2 ]) // haskell hybrid

p`[ . ]`([ 1, 2 ])         // JS inspired, from `...` (-> false)
p`[ a, . ]`([ 1, 2 ])      // because why not?
p`[ ., b, ... ]`([ 1, 2 ]) // "full" JS
```
Honestly, I find `[.]` quite intriguing.
It's tied for the lead with Haskell style.

**Comment by ryardley** [comment]
I really like the idea of using `.` with `...` - it has a poetry about it however there are problems with this in my opinion I outline below.

Some reasons I prefer `*` over `_`, `.` or `?` 
1. `_` and `.` are both easy to miss where as `*` leaps out at you. It is really easy to spot that it's a wildcard. When I look at the syntax in my mind I am trying to match up the wildcards with their concrete versions to find the pattern in the array of the things that change versus the things that are bound by types - this is easier with `*` - `#` would work too here but it doesn't have much else in it's favour and we are thinking of using it for error messages.
1. Even junior programmers will be a little familiar with `*` as it is used as a wildcard in globbing syntax when dealing with files. Eg. `*.js` This is common on both Windows, Mac and linux filesystems and many people come across this before they start to program.
1. I am not so concerned RegEx familiarity of `*` as RegEx is something few junior intermediate programmers learn - I find it there is usually only one or two people on a team who are particularly good at it.
1. `?` is now the optional chaining operator which will get confusing as it is designed around property access something this library could potentially be concerned with in the future. This rules out `?` in my opinion.
1. I am comfortable saying that we will never need arithmetic in the library where as there is a chance we may need `.` for property access as mentioned above. This rules out `.` in my opinion.
1. `*` in Flow acted as the existential operator which has exactly this function (even though is has now been deprecated) 
1. `_` is actually a valid javascript variable name where as `*` is not this became a thing when mirroring all the primitives in JS and bringing JS values into the lang. 
1. `any` could be a possibility although `any` can also be `undefined` and I think it is too long and too associated with TypeScript specifically it's also a valid var name.

Whatever the wildcard symbol is it will need to stand in for a predicate that checks existence which means it must the following will be equivalent:

```js
p`{ name }`;

// will be the same as the following:
p`{ name: * }`;

// or if we use `_`

p`{ name: _ }`;
```

**Comment by ZabutonNage** [comment]
Even though I got to like `.` quite much, bigger tasks seem to be waiting for it and I agree it would be reasonable to reserve it for those.

Familiarity is something I hardly ever consider when making long term decisions because it can (and should) be overcome so easily, basically overnight.

I'm not quite convinced that `_` being a valid JS name could pose a problem here. It would only be used in pattern-land. There we don't ever use identifiers which it could clash with. It's either types or concrete values if I'm not mistaken.
```js
const _ = "foo";
p`[number, _, "foo"]`([123, "not foo", _]) // true
```
Unless custom types are supported and one happens to be called `_`, I don't see any issues.
And even if the initially proposed object key wildcard (``p`{ * }` ``) was introduced, `*` wouldn't have an advantage over `_` for not being a valid name. `{ "*": 0 }` is just as valid as `{ _: 0 }` is and we couldn't enforce the existence of this very key either way.

But who knows? Perhaps custom types will be supported some day (or already are). Furthermore you stated there might be a different job for `_` which it would be a better fit for.
Although I would have liked to see JS evolve into a more haskellesque thing and `_` remains my personal favourite, `*` might have a slightly smaller chance of syntax clashes later on.

**Comment by ZabutonNage** [comment]
The term _existential operator_ occurred a few times. Just to clarify the workings of the single element wildcard. As a wilrdcard it should match anything without exception.
```js
p`[number, *]`([123, undefined]); // true
```
Because otherwise at least the length match wouldn't work reliably anymore.
```js
// arr1.length == arr2.length == 1
p`[*]`(arr1); // true
p`[*]`(arr2); // false, WAT??
```
This would happen if `arr1 = ["foo"]` and `arr2 = [undefined]`.

**Distinguished approach**
An existential operator is a different concept which could be interesting to look into separately.
Perhaps this even opens the doors for `_` to come back.
```js
const arr1 = ["foo"]; // length 1
p`[*]`(arr1); // true
p`[_]`(arr1); // true

const arr2 = [undefined]; // length 1
p`[*]`(arr2); // false - now correct
p`[_]`(arr2); // true  - being the "don't care about nullishness" wildcard
```

**Comment by ryardley** [comment]
That is a really interesting point. Personally I would intuitively expect `*` to include `undefined` and `_` to not. I would be happy to implement that?

**Comment by ZabutonNage** [comment]
A non-nullish wildcard would be a great addition I think. Thinking about the `notNil` example from the README:
```js
// before
const notNil = p`!(null|undefined)`;
// after
const notNil = p`_`;
```

Back to objects, maybe I'm thinking of this too much with a pattern matching mindset.
In an _exact by default_ context I would expect
```js
p`{ name }`({ name: undefined }); // true - because property is present
```
Hence corresponding to (assuming `*` becomes the nullish-inclusive wildcard)
```js
p`{ name: * }`({ name: undefined }); // true
```
Same applies to non-nullish falsy values
```js
p`{ status, age }`({ status: "newborn", age: 0 }); // currently false, but true might be more intuitive
```
Currently the focus is on a property's value. But if I only specify an object's key, I would assume that the focus is on the key and the value is not of interest. With wildcards we achieve very fine-grained control over this and we might be able to adjust this together with the change from _loose by default_ to _exact by default_.

However, this might mean that the checking for truthiness could no longer be implicit. While it would remain possible, it would become more verbose.
Running the risk of introducing too much at the same time, there could still be a viable way to keep truthy/falsy checks short and expressive. A pair of pseudo-type keywords could solve this.
```js
p`{ foo: truthy }`({ foo: 1 }); // true
p`{ foo: truthy }`({ foo: 0 }); // false
p`{ foo }`({ foo: 0 }); // true
p`{ foo: falsy }`({ foo: 1 }); // false
p`{ foo: falsy }`({ foo: 0 }); // true
p`{ foo: falsy }`({ foo: "falsy" }); // false
p`{ foo: "falsy" }`({ foo: "falsy" }); // true
```
This would be in line with current type handling
```js
p`{ foo: number }`({ foo: "number" }); // false
p`{ foo: "number" }`({ foo: "number" }); // true
```
And it would also promote the philosophy of being explicit about expected behaviour which _exact by default_ already does.

But I really don't know if this goes against the overall philosophy of pdsl.
I was hoping to write a shorter comment this time but this issue seems to require much more consideration than initially expected.

**Comment by ryardley** [comment]
> A non-nullish wildcard would be a great addition I think. Thinking about the notNil example from the README:

Yes I had the same thought wasn't sure if `_` should include null or not but I am warming pretty rapidly to the idea because of the usage example below:

>Back to objects, maybe I'm thinking of this too much with a pattern matching mindset.
In an exact by default context I would expect...

My default position before was to make it so the default would specify the setting of the property but honestly on thinking about how people will likely approach this lib I think it would cause confusion especially if you have stuff like:

```js
myObj.name = await myservice.getAName(); // returns undefined (or null)
if(p`!{name}`(myObj)){
  // throw an error or something 
}
```

I think notNil applies pretty well here so I am starting to think we should have `_` be the equivalent to notNil and that be the default property existence definition: 

```js
p`{ name }`;
// same as
p`{ name: _ }`;
// same as
p`{ name: !( null | undefined ) }`;

// if you want to just check for property name having been set "in" the object you can use `*`
p`{ name: * }` (mightSetNameProp(obj));

// If you want to be really picky about undefined vs null you can define your own predicate
const isNotUndefined = p`!undefined`;
p`{ name: ${isNotUndefined} }`({name:null}); // true
```

Maybe later we can pick a symbol for this? Any ideas? In any case we can introduce it later.

`falsy` | `truthy` I am not so sure about yet. I would prefer something like `!` for falsy and `!!` for truthy as it corresponds with what is intuitive in javascript.

**Comment by ZabutonNage** [comment]
``p`{name: !}` `` is not yet implemented, is it? I tried it quickly but it seems to yield a constant result no matter the input.
But yes, `!` and `!!` would be much nicer than `truthy`/`falsy`.

Well, I think I can't add much more here.
I still think that the minimum notation should map to the minimum amount of information available which in my eyes is a key's existence. Everything beyond minimum deserves explicit notation.
But, again, this is **my** personal approach. You can make much more accurate assumptions about your users' approach in order to find the most appropriate defaults.

At last, all necessary topics seem to have been addressed.
Or is there anything left?

**Comment by ryardley** [comment]
Hmm sorry I thought I had already implemented it. I will add bang predicates as a task. Thanks for this discussion I expect to get this done by the end of October.

**Comment by ryardley** [comment]
@ZabutonNage so in implementing this I have noticed that this has the unfortunate side effect of making it so when checking string length we need to include the rest parameter.

```js
expect(p`string & { length: 6, ... }`("123456")).toBe(true);
```

This makes something that is already verbose more so. Not sure what to do about this. 

Thinking perhaps:

```
expect(p`string[6]`("123456")).toBe(true);
```

**Comment by ryardley** [comment]
Or should we simply use the primative as the contents check instead? 

```js
p`string[6]`("123456"); // true
p`string[6]`("12345"); // false
p`number[6]`([1,2,3,4,5,6]); // true
p`number[6]`([1,2,3,'4',5,6]); // false
```

**Comment by ryardley** [comment]
Hmm that has ramifications though where we need to provide any predicate ahead of the bracket notation.

```js
p`{ name: string }[2]`([{name:'Fred'}, {name:'Mary'}]); // true
p`{ name: string }[2]`([{name:'Fred'}, {name:'Mary'}, {name:'Ken'}]); // false
```

**Comment by ryardley** [comment]
This would still mean we can have things like this: 
```js
p`[ {name:string}, number , * ]`([{name:'Foo'}, 1, undefined]); // true
```

**Comment by ryardley** [comment]
So it turns out that the array checking syntax with an ambiguous postfix operator is a really difficult syntax to parse. I am probably going to have to go with the alternative typescript syntax of `Array<predicate>` which is much easier event though it is still has the ambiguous trailing `>` it is less so.

**Comment by ryardley** [comment]
Disambiguating stuff like this was proving too difficult `{name:{name: [number]}[7]}`

Reverting to:

```js
// This is done
Array<type> // for typed arrays
[number, string, *, _, ...] // Specific match with rest param

// Think I can do the following but might be challenging
array[>10] // Length check on "array" only
string[>10] // Length check on "string" only
```

**Comment by ryardley** [comment]
This is now available for testing under `pdsl@next`

**Comment by ZabutonNage** [comment]
Hi @ryardley, seems you have settled on a solution already. Sorry I couldn't find the time to reply sooner.

I understand that a suffix `[1]` is now a length contraint which only applies to `array` and `string`, correct?
I wonder whether this has potential for complications in the future because it wires syntax to the `length` property. Could there ever be another property that needs special treatment? Would that one require more special syntax? Would we ever run out of available syntax?

First thing that came to my mind reading your latest comments is, whether a kind of modifier syntax could be worth exploring. This would be limited to selected properties like `length` that are present on an object but don't appear in `Object.keys`.
```js
p`Array.length(2)`([1,"2"]); // true
p`Array<number>.length(2)`([1,2]); // true
p`[number, ...].length(<5)`(1, 2, 3); // true
```
A bit verbose but it wouldn't hard-wire syntax to a property. Extensions like this could easily be implemented:
```js
p`String.foo(123)`("some string")
```
Whatever that would mean.

But at the moment I can't think of a property other than `length`. Perhaps it's just not necessary.

**Comment by ryardley** [comment]
Yeah I doubt we need more here. Length checking is extremely common other cases are not as important and we can live with a little verbosity. Here I have tried to follow TypeScript's precedence which works well. Any other property can be managed using the more verbose syntax you can also use for length: 

```
p`string & ( length: 10, ... )`('1234567890'); 
p`symbol & {valueOf:Function, ... }`(Symbol('foo')); // Contrived example
```

In the future I would like to make it so like in TypeScript, arrays can be inferred by providing a type and following with `[]` - eg. `{foo:string}[>6]`. I tried to do this but was running into issues with disambiguation which I need more time than I have right now to solve.

**Comment by ryardley** [comment]
Bumping this thread. Working with exact matching syntax on objects in the wild has proven too difficult and cumbersome to maintain and actively works against the main goals of this library which is to provide a great concise data validation experience. This is especially true in situations where you are checking things like GraphQL results, events, input arguments - honestly just about anything. At the same time the exact matching array syntax is very useful however we still need an array includes syntax. So I have pushed a breaking release to the `next` tag and I recommend everyone upgrade as it will be pushed live to the latest branch over the next few days to be used with BlitzJS.

Exact matching on objects is now off by default:

```js
p`{ name: "foo" }`({name: "foo", age: 20}); // true
```

Exact object matching mode can be turned on by using objects with pipes `|`:

```js
p`{| name: "foo" |}`({name: "foo", age: 20}); // false
```

Once you turn exact matching on in an object tree you can only turn it off by using the rest operator:

```js
```
